/**
 * $LastChangedBy: Andre $
 * $LastChangedDate: 2016-07-07 09:50:33 +0200 (Thu, 07 Jul 2016) $
 * $LastChangedRevision: 994 $
 */
package com.stellr.util;

import java.util.ArrayList;
import java.util.List;

public class CountryListUtil {
    
    private static final List<String> COUNTRY_LIST = new ArrayList<>();
    
    public static List<String> GetCountryList() {
        if(COUNTRY_LIST.isEmpty()) {
            MakeList();
        }
        return COUNTRY_LIST;
    }
    
    private static void MakeList(){
        COUNTRY_LIST.add("");
        COUNTRY_LIST.add("India");
        COUNTRY_LIST.add("South Africa");
        COUNTRY_LIST.add("----------------------------------------------------");
        COUNTRY_LIST.add("Afghanistan");
        COUNTRY_LIST.add("Albania");
        COUNTRY_LIST.add("Algeria");
        COUNTRY_LIST.add("Andorra");
        COUNTRY_LIST.add("Angola");
        COUNTRY_LIST.add("Antigua and Barbuda");
        COUNTRY_LIST.add("Argentina");
        COUNTRY_LIST.add("Armenia");
        COUNTRY_LIST.add("Australia");
        COUNTRY_LIST.add("Austria");
        COUNTRY_LIST.add("Azerbaijan");
        COUNTRY_LIST.add("Bahamas, The");
        COUNTRY_LIST.add("Bahrain");
        COUNTRY_LIST.add("Bangladesh");
        COUNTRY_LIST.add("Barbados");
        COUNTRY_LIST.add("Belarus");
        COUNTRY_LIST.add("Belgium");
        COUNTRY_LIST.add("Belize");
        COUNTRY_LIST.add("Benin");
        COUNTRY_LIST.add("Bhutan");
        COUNTRY_LIST.add("Bolivia");
        COUNTRY_LIST.add("Bosnia and Herzegovina");
        COUNTRY_LIST.add("Botswana");
        COUNTRY_LIST.add("Brazil");
        COUNTRY_LIST.add("Brunei");
        COUNTRY_LIST.add("Bulgaria");
        COUNTRY_LIST.add("Burkina Faso");
        COUNTRY_LIST.add("Burundi");
        COUNTRY_LIST.add("Cambodia");
        COUNTRY_LIST.add("Cameroon");
        COUNTRY_LIST.add("Canada");
        COUNTRY_LIST.add("Cape Verde");
        COUNTRY_LIST.add("Central African Republic");
        COUNTRY_LIST.add("Chad");
        COUNTRY_LIST.add("Chile");
        COUNTRY_LIST.add("China, People's Republic of");
        COUNTRY_LIST.add("Colombia");
        COUNTRY_LIST.add("Comoros");
        COUNTRY_LIST.add("Congo, Democratic Republic of the");
        COUNTRY_LIST.add("Congo, Republic of the");
        COUNTRY_LIST.add("Costa Rica");
        COUNTRY_LIST.add("Cote d'Ivoire (Ivory Coast)");
        COUNTRY_LIST.add("Croatia");
        COUNTRY_LIST.add("Cuba");
        COUNTRY_LIST.add("Cyprus");
        COUNTRY_LIST.add("Czech Republic");
        COUNTRY_LIST.add("Denmark");
        COUNTRY_LIST.add("Djibouti");
        COUNTRY_LIST.add("Dominica");
        COUNTRY_LIST.add("Dominican Republic");
        COUNTRY_LIST.add("Ecuador");
        COUNTRY_LIST.add("Egypt");
        COUNTRY_LIST.add("El Salvador");
        COUNTRY_LIST.add("Equatorial Guinea");
        COUNTRY_LIST.add("Eritrea");
        COUNTRY_LIST.add("Estonia");
        COUNTRY_LIST.add("Ethiopia");
        COUNTRY_LIST.add("Fiji");
        COUNTRY_LIST.add("Finland");
        COUNTRY_LIST.add("France");
        COUNTRY_LIST.add("Gabon");
        COUNTRY_LIST.add("Gambia, The");
        COUNTRY_LIST.add("Georgia");
        COUNTRY_LIST.add("Germany");
        COUNTRY_LIST.add("Ghana");
        COUNTRY_LIST.add("Greece");
        COUNTRY_LIST.add("Grenada");
        COUNTRY_LIST.add("Guatemala");
        COUNTRY_LIST.add("Guinea");
        COUNTRY_LIST.add("Guinea-Bissau");
        COUNTRY_LIST.add("Guyana");
        COUNTRY_LIST.add("Haiti");
        COUNTRY_LIST.add("Honduras");
        COUNTRY_LIST.add("Hungary");
        COUNTRY_LIST.add("Iceland");
        COUNTRY_LIST.add("Indonesia");
        COUNTRY_LIST.add("Iran");
        COUNTRY_LIST.add("Iraq");
        COUNTRY_LIST.add("Ireland");
        COUNTRY_LIST.add("Israel");
        COUNTRY_LIST.add("Italy");
        COUNTRY_LIST.add("Jamaica");
        COUNTRY_LIST.add("Japan");
        COUNTRY_LIST.add("Jordan");
        COUNTRY_LIST.add("Kazakhstan");
        COUNTRY_LIST.add("Kenya");
        COUNTRY_LIST.add("Kiribati");
        COUNTRY_LIST.add("Korea, Democratic People's Republic of (North Korea)");
        COUNTRY_LIST.add("Korea, Republic of (South Korea)");
        COUNTRY_LIST.add("Kuwait");
        COUNTRY_LIST.add("Kyrgyzstan");
        COUNTRY_LIST.add("Laos");
        COUNTRY_LIST.add("Latvia");
        COUNTRY_LIST.add("Lebanon");
        COUNTRY_LIST.add("Lesotho");
        COUNTRY_LIST.add("Liberia");
        COUNTRY_LIST.add("Libya");
        COUNTRY_LIST.add("Liechtenstein");
        COUNTRY_LIST.add("Lithuania");
        COUNTRY_LIST.add("Luxembourg");
        COUNTRY_LIST.add("Macedonia");
        COUNTRY_LIST.add("Madagascar");
        COUNTRY_LIST.add("Malawi");
        COUNTRY_LIST.add("Malaysia");
        COUNTRY_LIST.add("Maldives");
        COUNTRY_LIST.add("Mali");
        COUNTRY_LIST.add("Malta");
        COUNTRY_LIST.add("Marshall Islands");
        COUNTRY_LIST.add("Mauritania");
        COUNTRY_LIST.add("Mauritius");
        COUNTRY_LIST.add("Mexico");
        COUNTRY_LIST.add("Micronesia");
        COUNTRY_LIST.add("Moldova");
        COUNTRY_LIST.add("Monaco");
        COUNTRY_LIST.add("Mongolia");
        COUNTRY_LIST.add("Montenegro");
        COUNTRY_LIST.add("Morocco");
        COUNTRY_LIST.add("Mozambique");
        COUNTRY_LIST.add("Myanmar (Burma)");
        COUNTRY_LIST.add("Namibia");
        COUNTRY_LIST.add("Nauru");
        COUNTRY_LIST.add("Nepal");
        COUNTRY_LIST.add("Netherlands");
        COUNTRY_LIST.add("New Zealand");
        COUNTRY_LIST.add("Nicaragua");
        COUNTRY_LIST.add("Niger");
        COUNTRY_LIST.add("Nigeria");
        COUNTRY_LIST.add("Norway");
        COUNTRY_LIST.add("Oman");
        COUNTRY_LIST.add("Pakistan");
        COUNTRY_LIST.add("Palau");
        COUNTRY_LIST.add("Panama");
        COUNTRY_LIST.add("Papua New Guinea");
        COUNTRY_LIST.add("Paraguay");
        COUNTRY_LIST.add("Peru");
        COUNTRY_LIST.add("Philippines");
        COUNTRY_LIST.add("Poland");
        COUNTRY_LIST.add("Portugal");
        COUNTRY_LIST.add("Qatar");
        COUNTRY_LIST.add("Romania");
        COUNTRY_LIST.add("Russia");
        COUNTRY_LIST.add("Rwanda");
        COUNTRY_LIST.add("Saint Kitts and Nevis");
        COUNTRY_LIST.add("Saint Lucia");
        COUNTRY_LIST.add("Saint Vincent and the Grenadines");
        COUNTRY_LIST.add("Samoa");
        COUNTRY_LIST.add("San Marino");
        COUNTRY_LIST.add("Sao Tome and Principe");
        COUNTRY_LIST.add("Saudi Arabia");
        COUNTRY_LIST.add("Senegal");
        COUNTRY_LIST.add("Serbia");
        COUNTRY_LIST.add("Seychelles");
        COUNTRY_LIST.add("Sierra Leone");
        COUNTRY_LIST.add("Singapore");
        COUNTRY_LIST.add("Slovakia");
        COUNTRY_LIST.add("Slovenia");
        COUNTRY_LIST.add("Solomon Islands");
        COUNTRY_LIST.add("Somalia");
        COUNTRY_LIST.add("Spain");
        COUNTRY_LIST.add("Sri Lanka");
        COUNTRY_LIST.add("Sudan");
        COUNTRY_LIST.add("Suriname");
        COUNTRY_LIST.add("Swaziland");
        COUNTRY_LIST.add("Sweden");
        COUNTRY_LIST.add("Switzerland");
        COUNTRY_LIST.add("Syria");
        COUNTRY_LIST.add("Tajikistan");
        COUNTRY_LIST.add("Tanzania");
        COUNTRY_LIST.add("Thailand");
        COUNTRY_LIST.add("Timor-Leste (East Timor)");
        COUNTRY_LIST.add("Togo");
        COUNTRY_LIST.add("Tonga");
        COUNTRY_LIST.add("Trinidad and Tobago");
        COUNTRY_LIST.add("Tunisia");
        COUNTRY_LIST.add("Turkey");
        COUNTRY_LIST.add("Turkmenistan");
        COUNTRY_LIST.add("Tuvalu");
        COUNTRY_LIST.add("Uganda");
        COUNTRY_LIST.add("Ukraine");
        COUNTRY_LIST.add("United Arab Emirates");
        COUNTRY_LIST.add("United Kingdom");
        COUNTRY_LIST.add("United States");
        COUNTRY_LIST.add("Uruguay");
        COUNTRY_LIST.add("Uzbekistan");
        COUNTRY_LIST.add("Vanuatu");
        COUNTRY_LIST.add("Vatican City");
        COUNTRY_LIST.add("Venezuela");
        COUNTRY_LIST.add("Vietnam");
        COUNTRY_LIST.add("Yemen");
        COUNTRY_LIST.add("Zambia");
        COUNTRY_LIST.add("Zimbabwe");
        COUNTRY_LIST.add("Abkhazia");
        COUNTRY_LIST.add("China, Republic of (Taiwan)");
        COUNTRY_LIST.add("Nagorno-Karabakh");
        COUNTRY_LIST.add("Northern Cyprus");
        COUNTRY_LIST.add("Pridnestrovie (Transnistria)");
        COUNTRY_LIST.add("Somaliland");
        COUNTRY_LIST.add("South Ossetia");
        COUNTRY_LIST.add("Ashmore and Cartier Islands");
        COUNTRY_LIST.add("Christmas Island");
        COUNTRY_LIST.add("Cocos (Keeling) Islands");
        COUNTRY_LIST.add("Coral Sea Islands");
        COUNTRY_LIST.add("Heard Island and McDonald Islands");
        COUNTRY_LIST.add("Norfolk Island");
        COUNTRY_LIST.add("New Caledonia");
        COUNTRY_LIST.add("French Polynesia");
        COUNTRY_LIST.add("Mayotte");
        COUNTRY_LIST.add("Saint Barthelemy");
        COUNTRY_LIST.add("Saint Martin");
        COUNTRY_LIST.add("Saint Pierre and Miquelon");
        COUNTRY_LIST.add("Wallis and Futuna");
        COUNTRY_LIST.add("French Southern and Antarctic Lands");
        COUNTRY_LIST.add("Clipperton Island");
        COUNTRY_LIST.add("Bouvet Island");
        COUNTRY_LIST.add("Cook Islands");
        COUNTRY_LIST.add("Niue");
        COUNTRY_LIST.add("Tokelau");
        COUNTRY_LIST.add("Guernsey");
        COUNTRY_LIST.add("Isle of Man");
        COUNTRY_LIST.add("Jersey");
        COUNTRY_LIST.add("Anguilla");
        COUNTRY_LIST.add("Bermuda");
        COUNTRY_LIST.add("British Indian Ocean Territory");
        COUNTRY_LIST.add("British Sovereign Base Areas");
        COUNTRY_LIST.add("British Virgin Islands");
        COUNTRY_LIST.add("Cayman Islands");
        COUNTRY_LIST.add("Falkland Islands (Islas Malvinas)");
        COUNTRY_LIST.add("Gibraltar");
        COUNTRY_LIST.add("Montserrat");
        COUNTRY_LIST.add("Pitcairn Islands");
        COUNTRY_LIST.add("Saint Helena");
        COUNTRY_LIST.add("South Georgia and the South Sandwich Islands");
        COUNTRY_LIST.add("Turks and Caicos Islands");
        COUNTRY_LIST.add("Northern Mariana Islands");
        COUNTRY_LIST.add("Puerto Rico");
        COUNTRY_LIST.add("American Samoa");
        COUNTRY_LIST.add("Baker Island");
        COUNTRY_LIST.add("Guam");
        COUNTRY_LIST.add("Howland Island");
        COUNTRY_LIST.add("Jarvis Island");
        COUNTRY_LIST.add("Johnston Atoll");
        COUNTRY_LIST.add("Kingman Reef");
        COUNTRY_LIST.add("Midway Islands");
        COUNTRY_LIST.add("Navassa Island");
        COUNTRY_LIST.add("Palmyra Atoll");
        COUNTRY_LIST.add("U.S. Virgin Islands");
        COUNTRY_LIST.add("Wake Island");
        COUNTRY_LIST.add("Hong Kong");
        COUNTRY_LIST.add("Macau");
        COUNTRY_LIST.add("Faroe Islands");
        COUNTRY_LIST.add("Greenland");
        COUNTRY_LIST.add("French Guiana");
        COUNTRY_LIST.add("Guadeloupe");
        COUNTRY_LIST.add("Martinique");
        COUNTRY_LIST.add("Reunion");
        COUNTRY_LIST.add("Aland");
        COUNTRY_LIST.add("Aruba");
        COUNTRY_LIST.add("Netherlands Antilles");
        COUNTRY_LIST.add("Svalbard");
        COUNTRY_LIST.add("Ascension");
        COUNTRY_LIST.add("Tristan da Cunha");
        COUNTRY_LIST.add("Antarctica");
        COUNTRY_LIST.add("Kosovo");
        COUNTRY_LIST.add("Palestinian Territories (Gaza Strip and West Bank)");
        COUNTRY_LIST.add("Western Sahara");
    }
}